name: Update JSON file with API data

on:
  push:
    branches: [master]

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch API data
        run: |
          curl -s http://dataservice.accuweather.com/forecasts/v1/daily/5day/27133?apikey=${{ secrets.API_KEY }}&details=true&metric=true > api_data.json

      - name: Read existing data from file
        id: read_file
        run: |
          if [ -f existing_data.json ]; then
            data=$(cat existing_data.json)
          else
            data="[]"
            echo "$data" > existing_data.json
          fi
          echo "::set-output name=data::$data"

      - name: Merge new data with existing data
        id: merge_data
        run: |
          new_data=$(cat api_data.json)
          existing_data=$(echo "${{ steps.read_file.outputs.data }}")
          merged_data=$(echo "$new_data" | jq --argjson existing "$existing_data" '. | unique + $existing | .[:10]')
          echo "$merged_data" > existing_data.json
          echo "::set-output name=data::$merged_data"
      - name: Commit changes
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git add existing_data.json
          git remote set-url origin https://${github_token}@github.com/${repository}
          git commit -m "Update existing_data.json with new API data"
          git push origin master
        env:
            user_name: "github-actions[bot]"
            user_email: "github-actions[bot]@users.noreply.github.com"
            github_token: ${{ secrets.ACCESS_TOKEN }}
            repository: ${{ github.repository }}
